name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            zlib1g-dev \
            libssl-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            libffi-dev \
            uuid-dev \
            android-tools-base

      - name: Set up Android SDK
        run: |
          mkdir -p android-sdk
          export ANDROID_HOME=$PWD/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-*_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools/
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager --install "platform-tools" "build-tools;33.0.0" "platforms;android-33" "ndk;25.2.9519653"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0" >> $GITHUB_ENV

      - name: Install AIDL
        run: |
          sudo apt-get update
          sudo apt-get install -y aidl
          sudo ln -s /usr/bin/aidl $ANDROID_HOME/build-tools/33.0.0/aidl || true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33

      - name: Update buildozer.spec
        run: |
          echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
          echo "android.build_tools_version = 33.0.0" >> buildozer.spec

      - name: Build APK
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          PATH: ${{ env.PATH }}
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-apk
          path: bin/*.apk
          retention-days: 7
